version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: "db"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python loansforgood/manage.py migrate &&
             python loansforgood/manage.py create_super_user &&
             python loansforgood/manage.py create_proposal_default_custom_fields &&
             python loansforgood/manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.docker
    depends_on:
      - db

  test:
    build:
      context: .
    volumes:
      - .:/app
    command: >
      sh -c "poetry install &&
            poetry run pytest -s loansforgood --cov=loansforgood/apps -l"
    env_file:
      - ./.env.docker
    depends_on:
      - db

  redis:
    image: redis:latest
    command: redis-server --port 6380
    volumes:
      - .:/app
    ports:
      - 6380:6380
    hostname: "redis"
    expose:
        - 6380

  celery:
    restart: always
    build:
      context: .
    command:
      sh -c "cd loansforgood &&
             celery -A loansforgood worker -l info"
    volumes:
      - .:/app
    env_file:
      - ./.env.docker
    depends_on:
      - redis
      - app
      - db

  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: yarn start

volumes:
  redis:
  postgres_data:
